### ISSUE TITLE
You really don't use sorted atoms right? (start, end)

### ISSUE THREAD

**Issue by hhhhzzzzz** [vsomnath/graphretro#1]
https://github.com/vsomnath/graphretro/blob/2a88730da980be59541780e790cdb0fbdc581828/seq_graph_retro/utils/parse.py#L127

**Comment by hhhhzzzzz** [comment]
Hi vsomnath,
    I'm very sorry to bother you. Could you tell me you really don't use the sorted atoms right? Thanks a lot!

Best,
hhhhzzzzz

**Comment by vsomnath** [comment]
Yeah, the sorted atoms are not really used here, because `a_start`, `a_end` are already in sorted order from the `get_bond_info` function
