### ISSUE TITLE
Reactant generation from product

### ISSUE THREAD

**Issue by ignaczgerg** [vsomnath/graphretro#3]
Hi! Is there a script to generate reactants from products? E.g. if I have a list of products, how can I generate the reactants from it? Thanks!

**Comment by vsomnath** [comment]
Hi, 

I think this script should be useful for you - https://github.com/vsomnath/graphretro/blob/main/scripts/eval/single_edit_lg.py

It takes the products from a CSV file, and predicts their reactants. 

Best,
Vignesh

**Comment by ignaczgerg** [comment]
Hi, Thanks! I made some tweeking in the single_edit_lg.py script and I was able to save them into a CSV as well. Thanks for the quick response!
