### ISSUE TITLE
Some Questions about training

### ISSUE THREAD

**Issue by zengkaipeng** [vsomnath/graphretro#5]
There are two different configs in the folds, one is for the Edit Prediction, what about another one? And two different settings are given in the article: Reaction class known and Reaction class unknown, how can I train the model under different settings

**Comment by vsomnath** [comment]
One is for edit prediction, the other is for synthon completion (or leaving group classification). 

You can change the `use_rxn_class` argument in any of the config files to `True` if you want to use reaction class information during training. This assumes that you also have the preprocessed features where the reaction class information (used as additional one hot feature for each atom) is saved to disk.

**Comment by zengkaipeng** [comment]
Thanks for your reply. I also want to know that what's the meaning of use_h_labels in the data preprocessing. It's something about how to create the initial atom feature for training?
