### ISSUE TITLE
missing functions in atom attention layer 

### ISSUE THREAD

**Issue by ANugmanova** [vsomnath/graphretro#7]
Good afternoon, I would like to try using the attention layer, but I noticed that the implementation of several functions in AtomAttention module is missing, such as create_scope_tensor, flat_to_batch, get_pair. Could you please add it or tell a little more about what they should do?

**Comment by vsomnath** [comment]
Hi, thank you for the question! 

I think I deleted them while cleaning up since the functions were largely never used outside of this, and the final model didn't use any attention. I will look for them in the private version if they are still there!

**Comment by ANugmanova** [comment]
Thanks a lot!

**Comment by vsomnath** [comment]
Hi, sorry, I could not find them in the private version either. Maybe this just carry forwarded over from stuff before.
