### ISSUE TITLE
Code enhancement

### ISSUE THREAD

**Issue by queliyong** [vsomnath/graphretro#8]
Hi,
At the "Limitations" part of the paper, "We leave it to future work to extend the model to realize a single reactant from multiple synthons". Is there any publication or code for this enhancement work to refer to? Thanks a lot.

**Comment by vsomnath** [comment]
Hi, as far as I am aware, this recent work attempts to do so - https://arxiv.org/pdf/2209.13178.pdf and addresses some drawbacks of GraphRetro, especially the low accuracies for higher `k` in a very elegant way. But I don't think the code for the same is available yet.
