### ISSUE TITLE
multi edit product problem

### ISSUE THREAD

**Issue by queliyong** [vsomnath/graphretro#9]
Hi,
Considering this multi edit product and it's corresponding reactants:
`C1=CC=C(N([H])C2=CC=CC=C2)C=C1.C1=CC=C(N([H])C2=CC=CC=C2)C=C1.C(Br)1=C([H])C([H])=C(C2=C([H])C([H])=C(Br)C([H])=C2[H])C([H])=C1[H]>>C1=CC=C(N(C2=CC=C(C3=CC=C(N(C4C=CC=CC=4)C4=CC=CC=C4)C=C3)C=C2)C2C=CC=CC=2)C=C1`
![A656EFFC-2CED-4b5b-95AE-65A40DA7DDA7](https://github.com/vsomnath/graphretro/assets/56716710/fe594389-52ea-4777-ae33-46f1803bd766)
The code and models this repo provided can not generate the reactants above, what can I do to generate this reactants. Thanks very much for your advice.

**Comment by vsomnath** [comment]
Hi, I think you could try either RetroXpert or any of the transformer models potentially.
